import type { Command } from 'commander';

import { writeFileSync, existsSync } from 'fs';
import { join } from 'path';
import pc from 'picocolors';

export function registerInit(program: Command): void {
  program
    .command('init')
    .description('Bootstrap a new Platform project in the current directory')
    .option('--url <url>', 'Platform installation URL')
    .option('--workspace <slug>', 'Default workspace slug')
    .action(async (opts: { url?: string; workspace?: string }) => {
      console.log(pc.bold('Initializing Platform project...'));

      const config = {
        platform: {
          url: opts.url ?? '',
          workspace: opts.workspace ?? '',
        },
      };

      const configFile = join(process.cwd(), 'platform.json');
      if (existsSync(configFile)) {
        console.error(pc.red('platform.json already exists. Remove it to reinitialize.'));
        process.exit(1);
      }

      writeFileSync(configFile, JSON.stringify(config, null, 2) + '\n', 'utf8');

      // Create .platform/ directory for generated types
      const typesDir = join(process.cwd(), '.platform');
      if (!existsSync(typesDir)) {
        const { mkdirSync } = await import('fs');
        mkdirSync(typesDir, { recursive: true });
        writeFileSync(
          join(typesDir, '.gitignore'),
          '# Generated by pdm sync-types\ntypes.ts\n',
          'utf8',
        );
      }

      console.log(pc.green('✓') + ' Created platform.json');
      console.log(pc.green('✓') + ' Created .platform/ (add to .gitignore or commit as desired)');
      console.log('');
      console.log('Next steps:');
      console.log('  ' + pc.cyan('pdm login --url <your-platform-url>'));
      console.log('  ' + pc.cyan('pdm sync-types --workspace <slug>'));
    });
}
