import type { Command } from 'commander';

import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import pc from 'picocolors';

import { requireConfig } from '../config.js';

export function registerSyncTypes(program: Command): void {
  program
    .command('sync-types')
    .description('Generate TypeScript types from a workspace schema')
    .requiredOption('--workspace <slug>', 'Workspace slug')
    .option('--schema <slug>', 'Schema slug (default: main)', 'main')
    .option('--out <path>', 'Output file path', '.platform/types.ts')
    .option('--format <format>', 'Output format: openapi | graphql | both (default: both)', 'both')
    .action(async (opts: { workspace: string; schema: string; out: string; format: string }) => {
      const cfg = requireConfig();

      console.log(pc.bold(`Syncing types for workspace ${pc.cyan(opts.workspace)}...`));

      const outPath = join(process.cwd(), opts.out);
      mkdirSync(join(outPath, '..'), { recursive: true });

      const parts: string[] = [
        '// Generated by pdm sync-types — do not edit manually',
        `// Workspace: ${opts.workspace}, Schema: ${opts.schema}`,
        `// Generated: ${new Date().toISOString()}`,
        '',
      ];

      if (opts.format === 'openapi' || opts.format === 'both') {
        const openApiTypes = await generateOpenApiTypes(
          cfg.url,
          cfg.token,
          opts.workspace,
          opts.schema,
        );
        parts.push(openApiTypes);
      }

      if (opts.format === 'graphql' || opts.format === 'both') {
        const gqlTypes = await generateGraphqlTypes(cfg.url, cfg.token, opts.workspace);
        if (gqlTypes) parts.push(gqlTypes);
      }

      writeFileSync(outPath, parts.join('\n'), 'utf8');
      console.log(pc.green('✓') + ` Types written to ${pc.cyan(opts.out)}`);
    });
}

async function generateOpenApiTypes(
  baseUrl: string,
  token: string,
  workspace: string,
  schema: string,
): Promise<string> {
  const openApiUrl = new URL(`/api/v1/data/${workspace}/openapi.json`, baseUrl);
  openApiUrl.searchParams.set('schema', schema);

  const { default: openapiTs, astToString } = await import('openapi-typescript');

  // Fetch the spec manually so we can inject the auth header
  const res = await fetch(openApiUrl, { headers: { Authorization: `Bearer ${token}` } });
  if (!res.ok) throw new Error(`Failed to fetch OpenAPI spec: ${res.status} ${res.statusText}`);
  const spec = await res.text();

  const ast = await openapiTs(spec);
  return astToString(ast);
}

async function generateGraphqlTypes(
  baseUrl: string,
  token: string,
  workspace: string,
): Promise<string | null> {
  const schemaUrl = `${baseUrl}/api/v1/graphql/${workspace}/schema`;
  const res = await fetch(schemaUrl, {
    headers: { Authorization: `Bearer ${token}` },
  });

  if (!res.ok) {
    // GraphQL might not be enabled for this workspace — not an error
    return null;
  }

  const sdl = await res.text();
  return [
    '// GraphQL schema types',
    `// Schema URL: ${schemaUrl}`,
    `export const graphqlSchema = \`${sdl.replace(/`/g, '\\`')}\`;`,
    '',
  ].join('\n');
}
