'use client';

import { Download } from 'lucide-react';
import { useState } from 'react';

import { Button } from '@/components/ui/button';

import { DocContent } from './components/DocContent';
import { DocMetaPanel } from './components/DocMetaPanel';
import { DocSearch } from './components/DocSearch';
import { DocSidebar } from './components/DocSidebar';
import { ExportDialog } from './dialogs/ExportDialog';

export type DocNavItem = {
  id: string;
  slug: string;
  title: string;
  autoGenerated: boolean;
  sourceType: string;
  children?: DocNavItem[];
};

const DEMO_NAV: DocNavItem[] = [
  {
    id: 'quickstart',
    slug: '/quickstart',
    title: 'Quickstart',
    autoGenerated: false,
    sourceType: 'human_maintained',
  },
  {
    id: 'domain',
    slug: '/domain',
    title: 'Domain Model',
    autoGenerated: true,
    sourceType: 'schema',
    children: [
      {
        id: 'contact',
        slug: '/domain/contact',
        title: 'Contact',
        autoGenerated: true,
        sourceType: 'schema',
      },
      {
        id: 'deal',
        slug: '/domain/deal',
        title: 'Deal',
        autoGenerated: true,
        sourceType: 'schema',
      },
      {
        id: 'note',
        slug: '/domain/note',
        title: 'Note',
        autoGenerated: true,
        sourceType: 'schema',
      },
    ],
  },
  {
    id: 'api',
    slug: '/api',
    title: 'API Reference',
    autoGenerated: true,
    sourceType: 'api_rest',
    children: [
      {
        id: 'api-rest',
        slug: '/api/rest',
        title: 'REST API',
        autoGenerated: true,
        sourceType: 'api_rest',
      },
      {
        id: 'api-graphql',
        slug: '/api/graphql',
        title: 'GraphQL',
        autoGenerated: true,
        sourceType: 'api_graphql',
      },
    ],
  },
  {
    id: 'components',
    slug: '/components',
    title: 'Components',
    autoGenerated: true,
    sourceType: 'ui_component',
    children: [
      {
        id: 'contacts-table',
        slug: '/components/contacts-table',
        title: 'ContactsTable',
        autoGenerated: true,
        sourceType: 'ui_component',
      },
      {
        id: 'deal-kanban',
        slug: '/components/deal-kanban',
        title: 'DealKanban',
        autoGenerated: true,
        sourceType: 'ui_component',
      },
    ],
  },
  {
    id: 'changelog',
    slug: '/changelog',
    title: 'Changelog',
    autoGenerated: true,
    sourceType: 'deployment_event',
  },
];

export default function ProjectDocsPage() {
  const [activePage, setActivePage] = useState<DocNavItem>(DEMO_NAV[0]);
  const [showExport, setShowExport] = useState(false);

  return (
    <div className="flex flex-col h-full">
      <div className="mb-5 flex items-start justify-between gap-4">
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            gap: 16,
            width: '100%',
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: 16, flex: 1, minWidth: 0 }}>
            <h1
              style={{
                fontSize: 14,
                fontWeight: 600,
                margin: 0,
                flexShrink: 0,
              }}
            >
              Project Docs
            </h1>
            <DocSearch onNavigate={setActivePage} navItems={DEMO_NAV} />
          </div>
          <div className="flex shrink-0 items-center gap-2">
            <Button
              variant="outline"
              size="sm"
              type="button"
              onClick={() => {
                setShowExport(true);
              }}
            >
              <Download style={{ width: 14, height: 14, marginRight: 6 }} />
              Export Site
            </Button>
          </div>
        </div>
      </div>

      <div style={{ display: 'flex', flex: 1, minHeight: 0 }}>
        <DocSidebar items={DEMO_NAV} activePage={activePage} onNavigate={setActivePage} />

        <div style={{ flex: 1, minWidth: 0, overflowY: 'auto' }}>
          <DocContent page={activePage} />
        </div>

        <DocMetaPanel page={activePage} />
      </div>

      {showExport && (
        <ExportDialog
          onClose={() => {
            setShowExport(false);
          }}
        />
      )}
    </div>
  );
}
