'use client';

import { useState } from 'react';
import { DocSidebar } from './components/DocSidebar';
import { DocContent } from './components/DocContent';
import { DocMetaPanel } from './components/DocMetaPanel';
import { DocSearch } from './components/DocSearch';
import { Button } from '@/components/ui/button';
import { Download } from 'lucide-react';
import { ExportDialog } from './dialogs/ExportDialog';

export type DocNavItem = {
  id: string;
  slug: string;
  title: string;
  autoGenerated: boolean;
  sourceType: string;
  children?: DocNavItem[];
};

const DEMO_NAV: DocNavItem[] = [
  { id: 'quickstart', slug: '/quickstart', title: 'Quickstart', autoGenerated: false, sourceType: 'human_maintained' },
  {
    id: 'domain', slug: '/domain', title: 'Domain Model', autoGenerated: true, sourceType: 'schema',
    children: [
      { id: 'contact', slug: '/domain/contact', title: 'Contact', autoGenerated: true, sourceType: 'schema' },
      { id: 'deal', slug: '/domain/deal', title: 'Deal', autoGenerated: true, sourceType: 'schema' },
      { id: 'note', slug: '/domain/note', title: 'Note', autoGenerated: true, sourceType: 'schema' },
    ],
  },
  {
    id: 'api', slug: '/api', title: 'API Reference', autoGenerated: true, sourceType: 'api_rest',
    children: [
      { id: 'api-rest', slug: '/api/rest', title: 'REST API', autoGenerated: true, sourceType: 'api_rest' },
      { id: 'api-graphql', slug: '/api/graphql', title: 'GraphQL', autoGenerated: true, sourceType: 'api_graphql' },
    ],
  },
  {
    id: 'components', slug: '/components', title: 'Components', autoGenerated: true, sourceType: 'ui_component',
    children: [
      { id: 'contacts-table', slug: '/components/contacts-table', title: 'ContactsTable', autoGenerated: true, sourceType: 'ui_component' },
      { id: 'deal-kanban', slug: '/components/deal-kanban', title: 'DealKanban', autoGenerated: true, sourceType: 'ui_component' },
    ],
  },
  { id: 'changelog', slug: '/changelog', title: 'Changelog', autoGenerated: true, sourceType: 'deployment_event' },
];

export default function ProjectDocsPage() {
  const [activePage, setActivePage] = useState<DocNavItem>(DEMO_NAV[0]);
  const [showExport, setShowExport] = useState(false);

  return (
    <div className="flex flex-col h-full">
      <div className="border-b bg-background px-6 py-3 flex items-center justify-between gap-4">
        <div className="flex items-center gap-4 flex-1 min-w-0">
          <h1 className="text-base font-semibold shrink-0">Project Docs</h1>
          <DocSearch onNavigate={setActivePage} navItems={DEMO_NAV} />
        </div>
        <Button size="sm" variant="outline" onClick={() => setShowExport(true)}>
          <Download className="h-4 w-4 mr-2" />
          Export Site
        </Button>
      </div>

      <div className="flex flex-1 min-h-0">
        <DocSidebar
          items={DEMO_NAV}
          activePage={activePage}
          onNavigate={setActivePage}
        />

        <div className="flex-1 min-w-0 overflow-y-auto">
          <DocContent page={activePage} />
        </div>

        <DocMetaPanel page={activePage} />
      </div>

      {showExport && (
        <ExportDialog onClose={() => setShowExport(false)} />
      )}
    </div>
  );
}
