import type { CustomerRow, Filter } from '@platform/ports-persistence';

import type { CustomerTableDefinition, ColumnDefinition, NormalizedType } from '../schema-model.js';

// ── GraphQL filter input → Filter<CustomerRow> ────────────────────────────────
//
// GraphQL filters are plain objects matching the shape generated by
// schema-builder.ts (e.g. { email: { _eq: "alice" }, _and: [...] }).
// This adapter walks that shape and produces the Filter<CustomerRow> AST
// used by the repository layer.

type FilterInput = Record<string, unknown>;

export function adaptGraphQLFilter(
  input: FilterInput,
  table: CustomerTableDefinition,
): Filter<CustomerRow> | undefined {
  const columnMap = new Map<string, ColumnDefinition>(
    table.columns.map((c) => [snakeToCamel(c.name), c]),
  );

  return buildFilter(input, columnMap);
}

function buildFilter(
  input: FilterInput,
  columnMap: Map<string, ColumnDefinition>,
): Filter<CustomerRow> | undefined {
  const conditions: Filter<CustomerRow>[] = [];

  for (const [key, value] of Object.entries(input)) {
    if (value == null) continue;

    if (key === '_and') {
      if (!Array.isArray(value)) continue;
      const subFilters = value
        .map((v) => buildFilter(v as FilterInput, columnMap))
        .filter((f): f is Filter<CustomerRow> => f !== undefined);
      if (subFilters.length > 0) conditions.push({ _and: subFilters });
      continue;
    }

    if (key === '_or') {
      if (!Array.isArray(value)) continue;
      const subFilters = value
        .map((v) => buildFilter(v as FilterInput, columnMap))
        .filter((f): f is Filter<CustomerRow> => f !== undefined);
      if (subFilters.length > 0) conditions.push({ _or: subFilters });
      continue;
    }

    if (key === '_not') {
      const sub = buildFilter(value as FilterInput, columnMap);
      if (sub !== undefined) conditions.push({ _not: sub } as unknown as Filter<CustomerRow>);
      continue;
    }

    // Column-level filter
    const col = columnMap.get(key);
    if (!col || typeof value !== 'object') continue;

    const ops = value as Record<string, unknown>;
    const colCondition: Record<string, unknown> = {};

    for (const [op, opValue] of Object.entries(ops)) {
      if (opValue == null) continue;
      const coerced = coerceValue(opValue, op, col.type.kind);
      if (coerced !== undefined) {
        colCondition[op] = coerced;
      }
    }

    if (Object.keys(colCondition).length > 0) {
      conditions.push({ [col.name]: colCondition } as Filter<CustomerRow>);
    }
  }

  if (conditions.length === 0) return undefined;
  if (conditions.length === 1) return conditions[0] as Filter<CustomerRow>;
  return { _and: conditions };
}

function coerceValue(value: unknown, op: string, kind: NormalizedType['kind']): unknown {
  if (op === '_is_null') return Boolean(value);

  if (Array.isArray(value)) {
    return value.map((v) => coerceScalar(v, kind));
  }

  return coerceScalar(value, kind);
}

function coerceScalar(value: unknown, kind: NormalizedType['kind']): unknown {
  if (value == null) return value;
  const asStr =
    typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean'
      ? String(value)
      : '';
  switch (kind) {
    case 'integer':
    case 'bigint':
      return typeof value === 'number' ? value : parseInt(asStr, 10);
    case 'decimal':
      return typeof value === 'number' ? value : parseFloat(asStr);
    case 'boolean':
      return typeof value === 'boolean' ? value : value === 'true';
    default:
      return asStr;
  }
}

function snakeToCamel(name: string): string {
  return name.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase());
}
