import type { SchemaTemplate } from './index.js';

export const blogTemplate: SchemaTemplate = {
  id: 'tpl-blog',
  name: 'Blog',
  description: 'Authors, categories, posts, and comments — a standard publishing schema.',
  tables: [
    {
      id: 'tpl-blog-tbl-authors',
      name: 'authors',
      primaryKey: { kind: 'single', columnId: 'tpl-blog-col-authors-id' },
      columns: [
        {
          id: 'tpl-blog-col-authors-id',
          name: 'id',
          type: { kind: 'uuid' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'gen_random_uuid' },
        },
        {
          id: 'tpl-blog-col-authors-name',
          name: 'name',
          type: { kind: 'string', length: 255 },
          nullable: false,
          isPii: true,
          piiCategory: 'identification',
        },
        {
          id: 'tpl-blog-col-authors-email',
          name: 'email',
          type: { kind: 'string', length: 255 },
          nullable: false,
          isPii: true,
          piiCategory: 'contact',
        },
        { id: 'tpl-blog-col-authors-bio', name: 'bio', type: { kind: 'text' }, nullable: true },
        {
          id: 'tpl-blog-col-authors-created-at',
          name: 'created_at',
          type: { kind: 'timestamp_tz' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'now' },
        },
      ],
      indexes: [
        {
          id: 'tpl-blog-idx-authors-email',
          name: 'idx_authors_email',
          columns: [{ columnId: 'tpl-blog-col-authors-email', direction: 'asc' }],
          unique: true,
        },
      ],
      foreignKeys: [],
      constraints: [],
    },
    {
      id: 'tpl-blog-tbl-categories',
      name: 'categories',
      primaryKey: { kind: 'single', columnId: 'tpl-blog-col-categories-id' },
      columns: [
        {
          id: 'tpl-blog-col-categories-id',
          name: 'id',
          type: { kind: 'uuid' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'gen_random_uuid' },
        },
        {
          id: 'tpl-blog-col-categories-name',
          name: 'name',
          type: { kind: 'string', length: 100 },
          nullable: false,
        },
        {
          id: 'tpl-blog-col-categories-slug',
          name: 'slug',
          type: { kind: 'string', length: 100 },
          nullable: false,
        },
        {
          id: 'tpl-blog-col-categories-created-at',
          name: 'created_at',
          type: { kind: 'timestamp_tz' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'now' },
        },
      ],
      indexes: [
        {
          id: 'tpl-blog-idx-categories-slug',
          name: 'idx_categories_slug',
          columns: [{ columnId: 'tpl-blog-col-categories-slug', direction: 'asc' }],
          unique: true,
        },
      ],
      foreignKeys: [],
      constraints: [],
    },
    {
      id: 'tpl-blog-tbl-posts',
      name: 'posts',
      primaryKey: { kind: 'single', columnId: 'tpl-blog-col-posts-id' },
      columns: [
        {
          id: 'tpl-blog-col-posts-id',
          name: 'id',
          type: { kind: 'uuid' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'gen_random_uuid' },
        },
        {
          id: 'tpl-blog-col-posts-title',
          name: 'title',
          type: { kind: 'string', length: 500 },
          nullable: false,
        },
        {
          id: 'tpl-blog-col-posts-slug',
          name: 'slug',
          type: { kind: 'string', length: 500 },
          nullable: false,
        },
        { id: 'tpl-blog-col-posts-body', name: 'body', type: { kind: 'text' }, nullable: false },
        {
          id: 'tpl-blog-col-posts-author-id',
          name: 'author_id',
          type: { kind: 'uuid' },
          nullable: false,
        },
        {
          id: 'tpl-blog-col-posts-category-id',
          name: 'category_id',
          type: { kind: 'uuid' },
          nullable: true,
        },
        {
          id: 'tpl-blog-col-posts-published-at',
          name: 'published_at',
          type: { kind: 'timestamp_tz' },
          nullable: true,
        },
        {
          id: 'tpl-blog-col-posts-created-at',
          name: 'created_at',
          type: { kind: 'timestamp_tz' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'now' },
        },
        {
          id: 'tpl-blog-col-posts-updated-at',
          name: 'updated_at',
          type: { kind: 'timestamp_tz' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'now' },
        },
      ],
      indexes: [
        {
          id: 'tpl-blog-idx-posts-slug',
          name: 'idx_posts_slug',
          columns: [{ columnId: 'tpl-blog-col-posts-slug', direction: 'asc' }],
          unique: true,
        },
        {
          id: 'tpl-blog-idx-posts-published',
          name: 'idx_posts_published_at',
          columns: [{ columnId: 'tpl-blog-col-posts-published-at', direction: 'desc' }],
          unique: false,
        },
        {
          id: 'tpl-blog-idx-posts-author',
          name: 'idx_posts_author_id',
          columns: [{ columnId: 'tpl-blog-col-posts-author-id', direction: 'asc' }],
          unique: false,
        },
      ],
      foreignKeys: [
        {
          id: 'tpl-blog-fk-posts-author',
          name: 'fk_posts_author',
          columns: ['tpl-blog-col-posts-author-id'],
          referencedTableId: 'tpl-blog-tbl-authors',
          referencedColumns: ['tpl-blog-col-authors-id'],
          onDelete: 'restrict',
          onUpdate: 'no_action',
        },
        {
          id: 'tpl-blog-fk-posts-category',
          name: 'fk_posts_category',
          columns: ['tpl-blog-col-posts-category-id'],
          referencedTableId: 'tpl-blog-tbl-categories',
          referencedColumns: ['tpl-blog-col-categories-id'],
          onDelete: 'set_null',
          onUpdate: 'no_action',
        },
      ],
      constraints: [],
    },
    {
      id: 'tpl-blog-tbl-comments',
      name: 'comments',
      primaryKey: { kind: 'single', columnId: 'tpl-blog-col-comments-id' },
      columns: [
        {
          id: 'tpl-blog-col-comments-id',
          name: 'id',
          type: { kind: 'uuid' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'gen_random_uuid' },
        },
        {
          id: 'tpl-blog-col-comments-post-id',
          name: 'post_id',
          type: { kind: 'uuid' },
          nullable: false,
        },
        {
          id: 'tpl-blog-col-comments-author-name',
          name: 'author_name',
          type: { kind: 'string', length: 100 },
          nullable: false,
          isPii: true,
          piiCategory: 'identification',
        },
        {
          id: 'tpl-blog-col-comments-author-email',
          name: 'author_email',
          type: { kind: 'string', length: 255 },
          nullable: false,
          isPii: true,
          piiCategory: 'contact',
        },
        { id: 'tpl-blog-col-comments-body', name: 'body', type: { kind: 'text' }, nullable: false },
        {
          id: 'tpl-blog-col-comments-created-at',
          name: 'created_at',
          type: { kind: 'timestamp_tz' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'now' },
        },
      ],
      indexes: [
        {
          id: 'tpl-blog-idx-comments-post',
          name: 'idx_comments_post_id',
          columns: [{ columnId: 'tpl-blog-col-comments-post-id', direction: 'asc' }],
          unique: false,
        },
      ],
      foreignKeys: [
        {
          id: 'tpl-blog-fk-comments-post',
          name: 'fk_comments_post',
          columns: ['tpl-blog-col-comments-post-id'],
          referencedTableId: 'tpl-blog-tbl-posts',
          referencedColumns: ['tpl-blog-col-posts-id'],
          onDelete: 'cascade',
          onUpdate: 'no_action',
        },
      ],
      constraints: [],
    },
  ],
};
