import type { SchemaTemplate } from './index.js';

export const crmTemplate: SchemaTemplate = {
  id: 'tpl-crm',
  name: 'CRM',
  description:
    'Contacts, companies, deals, and activity tracking — a lightweight customer relationship management schema.',
  tables: [
    {
      id: 'tpl-crm-tbl-companies',
      name: 'companies',
      primaryKey: { kind: 'single', columnId: 'tpl-crm-col-companies-id' },
      columns: [
        {
          id: 'tpl-crm-col-companies-id',
          name: 'id',
          type: { kind: 'uuid' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'gen_random_uuid' },
        },
        {
          id: 'tpl-crm-col-companies-name',
          name: 'name',
          type: { kind: 'string', length: 255 },
          nullable: false,
        },
        {
          id: 'tpl-crm-col-companies-domain',
          name: 'domain',
          type: { kind: 'string', length: 255 },
          nullable: true,
        },
        {
          id: 'tpl-crm-col-companies-created-at',
          name: 'created_at',
          type: { kind: 'timestamp_tz' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'now' },
        },
        {
          id: 'tpl-crm-col-companies-updated-at',
          name: 'updated_at',
          type: { kind: 'timestamp_tz' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'now' },
        },
      ],
      indexes: [
        {
          id: 'tpl-crm-idx-companies-name',
          name: 'idx_companies_name',
          columns: [{ columnId: 'tpl-crm-col-companies-name', direction: 'asc' }],
          unique: false,
        },
      ],
      foreignKeys: [],
      constraints: [],
    },
    {
      id: 'tpl-crm-tbl-contacts',
      name: 'contacts',
      primaryKey: { kind: 'single', columnId: 'tpl-crm-col-contacts-id' },
      columns: [
        {
          id: 'tpl-crm-col-contacts-id',
          name: 'id',
          type: { kind: 'uuid' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'gen_random_uuid' },
        },
        {
          id: 'tpl-crm-col-contacts-first-name',
          name: 'first_name',
          type: { kind: 'string', length: 100 },
          nullable: false,
          isPii: true,
          piiCategory: 'identification',
        },
        {
          id: 'tpl-crm-col-contacts-last-name',
          name: 'last_name',
          type: { kind: 'string', length: 100 },
          nullable: false,
          isPii: true,
          piiCategory: 'identification',
        },
        {
          id: 'tpl-crm-col-contacts-email',
          name: 'email',
          type: { kind: 'string', length: 255 },
          nullable: true,
          isPii: true,
          piiCategory: 'contact',
        },
        {
          id: 'tpl-crm-col-contacts-phone',
          name: 'phone',
          type: { kind: 'string', length: 50 },
          nullable: true,
          isPii: true,
          piiCategory: 'contact',
        },
        {
          id: 'tpl-crm-col-contacts-company-id',
          name: 'company_id',
          type: { kind: 'uuid' },
          nullable: true,
        },
        {
          id: 'tpl-crm-col-contacts-created-at',
          name: 'created_at',
          type: { kind: 'timestamp_tz' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'now' },
        },
        {
          id: 'tpl-crm-col-contacts-updated-at',
          name: 'updated_at',
          type: { kind: 'timestamp_tz' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'now' },
        },
      ],
      indexes: [
        {
          id: 'tpl-crm-idx-contacts-email',
          name: 'idx_contacts_email',
          columns: [{ columnId: 'tpl-crm-col-contacts-email', direction: 'asc' }],
          unique: false,
        },
        {
          id: 'tpl-crm-idx-contacts-company',
          name: 'idx_contacts_company_id',
          columns: [{ columnId: 'tpl-crm-col-contacts-company-id', direction: 'asc' }],
          unique: false,
        },
      ],
      foreignKeys: [
        {
          id: 'tpl-crm-fk-contacts-company',
          name: 'fk_contacts_company',
          columns: ['tpl-crm-col-contacts-company-id'],
          referencedTableId: 'tpl-crm-tbl-companies',
          referencedColumns: ['tpl-crm-col-companies-id'],
          onDelete: 'set_null',
          onUpdate: 'no_action',
        },
      ],
      constraints: [],
    },
    {
      id: 'tpl-crm-tbl-deals',
      name: 'deals',
      primaryKey: { kind: 'single', columnId: 'tpl-crm-col-deals-id' },
      columns: [
        {
          id: 'tpl-crm-col-deals-id',
          name: 'id',
          type: { kind: 'uuid' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'gen_random_uuid' },
        },
        {
          id: 'tpl-crm-col-deals-title',
          name: 'title',
          type: { kind: 'string', length: 255 },
          nullable: false,
        },
        {
          id: 'tpl-crm-col-deals-amount',
          name: 'amount',
          type: { kind: 'decimal', precision: 15, scale: 2 },
          nullable: true,
        },
        {
          id: 'tpl-crm-col-deals-stage',
          name: 'stage',
          type: { kind: 'string', length: 50 },
          nullable: false,
          defaultValue: { kind: 'literal', value: 'prospecting' },
        },
        {
          id: 'tpl-crm-col-deals-contact-id',
          name: 'contact_id',
          type: { kind: 'uuid' },
          nullable: true,
        },
        {
          id: 'tpl-crm-col-deals-company-id',
          name: 'company_id',
          type: { kind: 'uuid' },
          nullable: true,
        },
        {
          id: 'tpl-crm-col-deals-closed-at',
          name: 'closed_at',
          type: { kind: 'timestamp_tz' },
          nullable: true,
        },
        {
          id: 'tpl-crm-col-deals-created-at',
          name: 'created_at',
          type: { kind: 'timestamp_tz' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'now' },
        },
        {
          id: 'tpl-crm-col-deals-updated-at',
          name: 'updated_at',
          type: { kind: 'timestamp_tz' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'now' },
        },
      ],
      indexes: [
        {
          id: 'tpl-crm-idx-deals-stage',
          name: 'idx_deals_stage',
          columns: [{ columnId: 'tpl-crm-col-deals-stage', direction: 'asc' }],
          unique: false,
        },
      ],
      foreignKeys: [
        {
          id: 'tpl-crm-fk-deals-contact',
          name: 'fk_deals_contact',
          columns: ['tpl-crm-col-deals-contact-id'],
          referencedTableId: 'tpl-crm-tbl-contacts',
          referencedColumns: ['tpl-crm-col-contacts-id'],
          onDelete: 'set_null',
          onUpdate: 'no_action',
        },
        {
          id: 'tpl-crm-fk-deals-company',
          name: 'fk_deals_company',
          columns: ['tpl-crm-col-deals-company-id'],
          referencedTableId: 'tpl-crm-tbl-companies',
          referencedColumns: ['tpl-crm-col-companies-id'],
          onDelete: 'set_null',
          onUpdate: 'no_action',
        },
      ],
      constraints: [],
    },
    {
      id: 'tpl-crm-tbl-activities',
      name: 'activities',
      primaryKey: { kind: 'single', columnId: 'tpl-crm-col-activities-id' },
      columns: [
        {
          id: 'tpl-crm-col-activities-id',
          name: 'id',
          type: { kind: 'uuid' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'gen_random_uuid' },
        },
        {
          id: 'tpl-crm-col-activities-type',
          name: 'type',
          type: { kind: 'string', length: 50 },
          nullable: false,
        },
        {
          id: 'tpl-crm-col-activities-subject',
          name: 'subject',
          type: { kind: 'string', length: 500 },
          nullable: true,
        },
        {
          id: 'tpl-crm-col-activities-contact-id',
          name: 'contact_id',
          type: { kind: 'uuid' },
          nullable: true,
        },
        {
          id: 'tpl-crm-col-activities-deal-id',
          name: 'deal_id',
          type: { kind: 'uuid' },
          nullable: true,
        },
        {
          id: 'tpl-crm-col-activities-occurred-at',
          name: 'occurred_at',
          type: { kind: 'timestamp_tz' },
          nullable: false,
        },
        {
          id: 'tpl-crm-col-activities-created-at',
          name: 'created_at',
          type: { kind: 'timestamp_tz' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'now' },
        },
      ],
      indexes: [
        {
          id: 'tpl-crm-idx-activities-contact',
          name: 'idx_activities_contact_id',
          columns: [{ columnId: 'tpl-crm-col-activities-contact-id', direction: 'asc' }],
          unique: false,
        },
        {
          id: 'tpl-crm-idx-activities-occurred',
          name: 'idx_activities_occurred_at',
          columns: [{ columnId: 'tpl-crm-col-activities-occurred-at', direction: 'desc' }],
          unique: false,
        },
      ],
      foreignKeys: [
        {
          id: 'tpl-crm-fk-activities-contact',
          name: 'fk_activities_contact',
          columns: ['tpl-crm-col-activities-contact-id'],
          referencedTableId: 'tpl-crm-tbl-contacts',
          referencedColumns: ['tpl-crm-col-contacts-id'],
          onDelete: 'set_null',
          onUpdate: 'no_action',
        },
        {
          id: 'tpl-crm-fk-activities-deal',
          name: 'fk_activities_deal',
          columns: ['tpl-crm-col-activities-deal-id'],
          referencedTableId: 'tpl-crm-tbl-deals',
          referencedColumns: ['tpl-crm-col-deals-id'],
          onDelete: 'set_null',
          onUpdate: 'no_action',
        },
      ],
      constraints: [],
    },
  ],
};
