import type { SchemaTemplate } from './index.js';

export const ecommerceTemplate: SchemaTemplate = {
  id: 'tpl-ecommerce',
  name: 'E-commerce',
  description: 'Customers, products, orders, and line items — a standard online store schema.',
  tables: [
    {
      id: 'tpl-ecom-tbl-customers',
      name: 'customers',
      primaryKey: { kind: 'single', columnId: 'tpl-ecom-col-customers-id' },
      columns: [
        {
          id: 'tpl-ecom-col-customers-id',
          name: 'id',
          type: { kind: 'uuid' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'gen_random_uuid' },
        },
        {
          id: 'tpl-ecom-col-customers-name',
          name: 'name',
          type: { kind: 'string', length: 255 },
          nullable: false,
          isPii: true,
          piiCategory: 'identification',
        },
        {
          id: 'tpl-ecom-col-customers-email',
          name: 'email',
          type: { kind: 'string', length: 255 },
          nullable: false,
          isPii: true,
          piiCategory: 'contact',
        },
        {
          id: 'tpl-ecom-col-customers-phone',
          name: 'phone',
          type: { kind: 'string', length: 50 },
          nullable: true,
          isPii: true,
          piiCategory: 'contact',
        },
        {
          id: 'tpl-ecom-col-customers-shipping-address',
          name: 'shipping_address',
          type: { kind: 'text' },
          nullable: true,
          isPii: true,
          piiCategory: 'contact',
        },
        {
          id: 'tpl-ecom-col-customers-created-at',
          name: 'created_at',
          type: { kind: 'timestamp_tz' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'now' },
        },
        {
          id: 'tpl-ecom-col-customers-updated-at',
          name: 'updated_at',
          type: { kind: 'timestamp_tz' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'now' },
        },
      ],
      indexes: [
        {
          id: 'tpl-ecom-idx-customers-email',
          name: 'idx_customers_email',
          columns: [{ columnId: 'tpl-ecom-col-customers-email', direction: 'asc' }],
          unique: true,
        },
      ],
      foreignKeys: [],
      constraints: [],
    },
    {
      id: 'tpl-ecom-tbl-products',
      name: 'products',
      primaryKey: { kind: 'single', columnId: 'tpl-ecom-col-products-id' },
      columns: [
        {
          id: 'tpl-ecom-col-products-id',
          name: 'id',
          type: { kind: 'uuid' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'gen_random_uuid' },
        },
        {
          id: 'tpl-ecom-col-products-name',
          name: 'name',
          type: { kind: 'string', length: 255 },
          nullable: false,
        },
        {
          id: 'tpl-ecom-col-products-description',
          name: 'description',
          type: { kind: 'text' },
          nullable: true,
        },
        {
          id: 'tpl-ecom-col-products-price',
          name: 'price',
          type: { kind: 'decimal', precision: 12, scale: 2 },
          nullable: false,
        },
        {
          id: 'tpl-ecom-col-products-stock-qty',
          name: 'stock_qty',
          type: { kind: 'integer' },
          nullable: false,
          defaultValue: { kind: 'literal', value: 0 },
        },
        {
          id: 'tpl-ecom-col-products-created-at',
          name: 'created_at',
          type: { kind: 'timestamp_tz' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'now' },
        },
        {
          id: 'tpl-ecom-col-products-updated-at',
          name: 'updated_at',
          type: { kind: 'timestamp_tz' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'now' },
        },
      ],
      indexes: [],
      foreignKeys: [],
      constraints: [],
    },
    {
      id: 'tpl-ecom-tbl-orders',
      name: 'orders',
      primaryKey: { kind: 'single', columnId: 'tpl-ecom-col-orders-id' },
      columns: [
        {
          id: 'tpl-ecom-col-orders-id',
          name: 'id',
          type: { kind: 'uuid' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'gen_random_uuid' },
        },
        {
          id: 'tpl-ecom-col-orders-customer-id',
          name: 'customer_id',
          type: { kind: 'uuid' },
          nullable: false,
        },
        {
          id: 'tpl-ecom-col-orders-status',
          name: 'status',
          type: { kind: 'string', length: 50 },
          nullable: false,
          defaultValue: { kind: 'literal', value: 'pending' },
        },
        {
          id: 'tpl-ecom-col-orders-total-amount',
          name: 'total_amount',
          type: { kind: 'decimal', precision: 12, scale: 2 },
          nullable: false,
        },
        {
          id: 'tpl-ecom-col-orders-placed-at',
          name: 'placed_at',
          type: { kind: 'timestamp_tz' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'now' },
        },
        {
          id: 'tpl-ecom-col-orders-created-at',
          name: 'created_at',
          type: { kind: 'timestamp_tz' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'now' },
        },
        {
          id: 'tpl-ecom-col-orders-updated-at',
          name: 'updated_at',
          type: { kind: 'timestamp_tz' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'now' },
        },
      ],
      indexes: [
        {
          id: 'tpl-ecom-idx-orders-customer',
          name: 'idx_orders_customer_id',
          columns: [{ columnId: 'tpl-ecom-col-orders-customer-id', direction: 'asc' }],
          unique: false,
        },
        {
          id: 'tpl-ecom-idx-orders-status',
          name: 'idx_orders_status',
          columns: [{ columnId: 'tpl-ecom-col-orders-status', direction: 'asc' }],
          unique: false,
        },
        {
          id: 'tpl-ecom-idx-orders-placed',
          name: 'idx_orders_placed_at',
          columns: [{ columnId: 'tpl-ecom-col-orders-placed-at', direction: 'desc' }],
          unique: false,
        },
      ],
      foreignKeys: [
        {
          id: 'tpl-ecom-fk-orders-customer',
          name: 'fk_orders_customer',
          columns: ['tpl-ecom-col-orders-customer-id'],
          referencedTableId: 'tpl-ecom-tbl-customers',
          referencedColumns: ['tpl-ecom-col-customers-id'],
          onDelete: 'restrict',
          onUpdate: 'no_action',
        },
      ],
      constraints: [],
    },
    {
      id: 'tpl-ecom-tbl-order-items',
      name: 'order_items',
      primaryKey: { kind: 'single', columnId: 'tpl-ecom-col-order-items-id' },
      columns: [
        {
          id: 'tpl-ecom-col-order-items-id',
          name: 'id',
          type: { kind: 'uuid' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'gen_random_uuid' },
        },
        {
          id: 'tpl-ecom-col-order-items-order-id',
          name: 'order_id',
          type: { kind: 'uuid' },
          nullable: false,
        },
        {
          id: 'tpl-ecom-col-order-items-product-id',
          name: 'product_id',
          type: { kind: 'uuid' },
          nullable: false,
        },
        {
          id: 'tpl-ecom-col-order-items-qty',
          name: 'qty',
          type: { kind: 'integer' },
          nullable: false,
        },
        {
          id: 'tpl-ecom-col-order-items-unit-price',
          name: 'unit_price',
          type: { kind: 'decimal', precision: 12, scale: 2 },
          nullable: false,
        },
        {
          id: 'tpl-ecom-col-order-items-created-at',
          name: 'created_at',
          type: { kind: 'timestamp_tz' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'now' },
        },
      ],
      indexes: [
        {
          id: 'tpl-ecom-idx-order-items-order',
          name: 'idx_order_items_order_id',
          columns: [{ columnId: 'tpl-ecom-col-order-items-order-id', direction: 'asc' }],
          unique: false,
        },
        {
          id: 'tpl-ecom-idx-order-items-product',
          name: 'idx_order_items_product_id',
          columns: [{ columnId: 'tpl-ecom-col-order-items-product-id', direction: 'asc' }],
          unique: false,
        },
      ],
      foreignKeys: [
        {
          id: 'tpl-ecom-fk-order-items-order',
          name: 'fk_order_items_order',
          columns: ['tpl-ecom-col-order-items-order-id'],
          referencedTableId: 'tpl-ecom-tbl-orders',
          referencedColumns: ['tpl-ecom-col-orders-id'],
          onDelete: 'cascade',
          onUpdate: 'no_action',
        },
        {
          id: 'tpl-ecom-fk-order-items-product',
          name: 'fk_order_items_product',
          columns: ['tpl-ecom-col-order-items-product-id'],
          referencedTableId: 'tpl-ecom-tbl-products',
          referencedColumns: ['tpl-ecom-col-products-id'],
          onDelete: 'restrict',
          onUpdate: 'no_action',
        },
      ],
      constraints: [],
    },
  ],
};
