import type { SchemaTemplate } from './index.js';

export const taskTrackerTemplate: SchemaTemplate = {
  id: 'tpl-task-tracker',
  name: 'Task tracker',
  description: 'Users, projects, tasks, and comments — a simple project management schema.',
  tables: [
    {
      id: 'tpl-tasks-tbl-users',
      name: 'users',
      primaryKey: { kind: 'single', columnId: 'tpl-tasks-col-users-id' },
      columns: [
        {
          id: 'tpl-tasks-col-users-id',
          name: 'id',
          type: { kind: 'uuid' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'gen_random_uuid' },
        },
        {
          id: 'tpl-tasks-col-users-name',
          name: 'name',
          type: { kind: 'string', length: 255 },
          nullable: false,
          isPii: true,
          piiCategory: 'identification',
        },
        {
          id: 'tpl-tasks-col-users-email',
          name: 'email',
          type: { kind: 'string', length: 255 },
          nullable: false,
          isPii: true,
          piiCategory: 'contact',
        },
        {
          id: 'tpl-tasks-col-users-created-at',
          name: 'created_at',
          type: { kind: 'timestamp_tz' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'now' },
        },
      ],
      indexes: [
        {
          id: 'tpl-tasks-idx-users-email',
          name: 'idx_users_email',
          columns: [{ columnId: 'tpl-tasks-col-users-email', direction: 'asc' }],
          unique: true,
        },
      ],
      foreignKeys: [],
      constraints: [],
    },
    {
      id: 'tpl-tasks-tbl-projects',
      name: 'projects',
      primaryKey: { kind: 'single', columnId: 'tpl-tasks-col-projects-id' },
      columns: [
        {
          id: 'tpl-tasks-col-projects-id',
          name: 'id',
          type: { kind: 'uuid' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'gen_random_uuid' },
        },
        {
          id: 'tpl-tasks-col-projects-name',
          name: 'name',
          type: { kind: 'string', length: 255 },
          nullable: false,
        },
        {
          id: 'tpl-tasks-col-projects-description',
          name: 'description',
          type: { kind: 'text' },
          nullable: true,
        },
        {
          id: 'tpl-tasks-col-projects-created-by',
          name: 'created_by',
          type: { kind: 'uuid' },
          nullable: false,
        },
        {
          id: 'tpl-tasks-col-projects-created-at',
          name: 'created_at',
          type: { kind: 'timestamp_tz' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'now' },
        },
        {
          id: 'tpl-tasks-col-projects-updated-at',
          name: 'updated_at',
          type: { kind: 'timestamp_tz' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'now' },
        },
      ],
      indexes: [],
      foreignKeys: [
        {
          id: 'tpl-tasks-fk-projects-created-by',
          name: 'fk_projects_created_by',
          columns: ['tpl-tasks-col-projects-created-by'],
          referencedTableId: 'tpl-tasks-tbl-users',
          referencedColumns: ['tpl-tasks-col-users-id'],
          onDelete: 'restrict',
          onUpdate: 'no_action',
        },
      ],
      constraints: [],
    },
    {
      id: 'tpl-tasks-tbl-tasks',
      name: 'tasks',
      primaryKey: { kind: 'single', columnId: 'tpl-tasks-col-tasks-id' },
      columns: [
        {
          id: 'tpl-tasks-col-tasks-id',
          name: 'id',
          type: { kind: 'uuid' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'gen_random_uuid' },
        },
        {
          id: 'tpl-tasks-col-tasks-title',
          name: 'title',
          type: { kind: 'string', length: 500 },
          nullable: false,
        },
        {
          id: 'tpl-tasks-col-tasks-description',
          name: 'description',
          type: { kind: 'text' },
          nullable: true,
        },
        {
          id: 'tpl-tasks-col-tasks-project-id',
          name: 'project_id',
          type: { kind: 'uuid' },
          nullable: false,
        },
        {
          id: 'tpl-tasks-col-tasks-assignee-id',
          name: 'assignee_id',
          type: { kind: 'uuid' },
          nullable: true,
        },
        {
          id: 'tpl-tasks-col-tasks-status',
          name: 'status',
          type: { kind: 'string', length: 50 },
          nullable: false,
          defaultValue: { kind: 'literal', value: 'open' },
        },
        {
          id: 'tpl-tasks-col-tasks-due-at',
          name: 'due_at',
          type: { kind: 'timestamp_tz' },
          nullable: true,
        },
        {
          id: 'tpl-tasks-col-tasks-created-at',
          name: 'created_at',
          type: { kind: 'timestamp_tz' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'now' },
        },
        {
          id: 'tpl-tasks-col-tasks-updated-at',
          name: 'updated_at',
          type: { kind: 'timestamp_tz' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'now' },
        },
      ],
      indexes: [
        {
          id: 'tpl-tasks-idx-tasks-project',
          name: 'idx_tasks_project_id',
          columns: [{ columnId: 'tpl-tasks-col-tasks-project-id', direction: 'asc' }],
          unique: false,
        },
        {
          id: 'tpl-tasks-idx-tasks-assignee',
          name: 'idx_tasks_assignee_id',
          columns: [{ columnId: 'tpl-tasks-col-tasks-assignee-id', direction: 'asc' }],
          unique: false,
        },
        {
          id: 'tpl-tasks-idx-tasks-status',
          name: 'idx_tasks_status',
          columns: [{ columnId: 'tpl-tasks-col-tasks-status', direction: 'asc' }],
          unique: false,
        },
      ],
      foreignKeys: [
        {
          id: 'tpl-tasks-fk-tasks-project',
          name: 'fk_tasks_project',
          columns: ['tpl-tasks-col-tasks-project-id'],
          referencedTableId: 'tpl-tasks-tbl-projects',
          referencedColumns: ['tpl-tasks-col-projects-id'],
          onDelete: 'cascade',
          onUpdate: 'no_action',
        },
        {
          id: 'tpl-tasks-fk-tasks-assignee',
          name: 'fk_tasks_assignee',
          columns: ['tpl-tasks-col-tasks-assignee-id'],
          referencedTableId: 'tpl-tasks-tbl-users',
          referencedColumns: ['tpl-tasks-col-users-id'],
          onDelete: 'set_null',
          onUpdate: 'no_action',
        },
      ],
      constraints: [],
    },
    {
      id: 'tpl-tasks-tbl-comments',
      name: 'comments',
      primaryKey: { kind: 'single', columnId: 'tpl-tasks-col-comments-id' },
      columns: [
        {
          id: 'tpl-tasks-col-comments-id',
          name: 'id',
          type: { kind: 'uuid' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'gen_random_uuid' },
        },
        {
          id: 'tpl-tasks-col-comments-task-id',
          name: 'task_id',
          type: { kind: 'uuid' },
          nullable: false,
        },
        {
          id: 'tpl-tasks-col-comments-author-id',
          name: 'author_id',
          type: { kind: 'uuid' },
          nullable: false,
        },
        {
          id: 'tpl-tasks-col-comments-body',
          name: 'body',
          type: { kind: 'text' },
          nullable: false,
        },
        {
          id: 'tpl-tasks-col-comments-created-at',
          name: 'created_at',
          type: { kind: 'timestamp_tz' },
          nullable: false,
          defaultValue: { kind: 'function', name: 'now' },
        },
      ],
      indexes: [
        {
          id: 'tpl-tasks-idx-comments-task',
          name: 'idx_comments_task_id',
          columns: [{ columnId: 'tpl-tasks-col-comments-task-id', direction: 'asc' }],
          unique: false,
        },
      ],
      foreignKeys: [
        {
          id: 'tpl-tasks-fk-comments-task',
          name: 'fk_comments_task',
          columns: ['tpl-tasks-col-comments-task-id'],
          referencedTableId: 'tpl-tasks-tbl-tasks',
          referencedColumns: ['tpl-tasks-col-tasks-id'],
          onDelete: 'cascade',
          onUpdate: 'no_action',
        },
        {
          id: 'tpl-tasks-fk-comments-author',
          name: 'fk_comments_author',
          columns: ['tpl-tasks-col-comments-author-id'],
          referencedTableId: 'tpl-tasks-tbl-users',
          referencedColumns: ['tpl-tasks-col-users-id'],
          onDelete: 'restrict',
          onUpdate: 'no_action',
        },
      ],
      constraints: [],
    },
  ],
};
