'use client';

import type { PrdSectionType } from '@platform/core';

import { RefreshCw } from 'lucide-react';
import { useState } from 'react';

import { SECTION_DISPLAY_NAMES } from '../utils/sectionMeta.js';

interface RegenerateSectionDialogProps {
  open: boolean;
  sectionType: PrdSectionType;
  onConfirm: (feedback: string) => void;
  onCancel: () => void;
}

export function RegenerateSectionDialog({
  open,
  sectionType,
  onConfirm,
  onCancel,
}: RegenerateSectionDialogProps) {
  const [feedback, setFeedback] = useState('');

  if (!open) return null;

  const handleConfirm = () => {
    onConfirm(feedback);
    setFeedback('');
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Escape') onCancel();
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50"
      role="dialog"
      aria-modal="true"
      aria-labelledby="regen-dialog-title"
      onKeyDown={handleKeyDown}
    >
      <div className="w-full max-w-md rounded-xl border bg-card shadow-xl">
        {/* Header */}
        <div className="flex items-center gap-3 border-b px-5 py-4">
          <RefreshCw className="h-5 w-5 text-primary" aria-hidden="true" />
          <h2 id="regen-dialog-title" className="text-base font-semibold text-foreground">
            Regenerate {SECTION_DISPLAY_NAMES[sectionType]}
          </h2>
        </div>

        {/* Body */}
        <div className="px-5 py-4 space-y-4">
          <p className="text-sm text-muted-foreground">
            The current section content will be discarded and regenerated by the AI. You can
            optionally provide feedback to guide the regeneration.
          </p>
          <div>
            <label
              htmlFor="regen-feedback"
              className="mb-1.5 block text-sm font-medium text-foreground"
            >
              Feedback <span className="text-muted-foreground">(optional)</span>
            </label>
            <textarea
              id="regen-feedback"
              className="w-full rounded-lg border bg-background px-3 py-2 text-sm placeholder-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary resize-none"
              rows={3}
              placeholder="e.g. Focus on enterprise personas, add more detail on SLA requirements…"
              value={feedback}
              onChange={(e) => {
                setFeedback(e.target.value);
              }}
              autoFocus
            />
          </div>
        </div>

        {/* Footer */}
        <div className="flex justify-end gap-2 border-t px-5 py-3">
          <button
            type="button"
            className="rounded-lg border px-4 py-2 text-sm hover:bg-muted"
            onClick={onCancel}
          >
            Cancel
          </button>
          <button
            type="button"
            className="flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90"
            onClick={handleConfirm}
          >
            <RefreshCw className="h-4 w-4" aria-hidden="true" />
            Regenerate
          </button>
        </div>
      </div>
    </div>
  );
}
