import { Result, ok, err } from 'neverthrow';
import type { RequestContext } from '../../../context.js';
import { NotFoundError, ValidationError } from '../../../errors.js';
import type {
  DocPage,
  DocSite,
  DocExport,
  DocTelemetryEvent,
  GenerateDocPageInput,
  UpdateDocPageInput,
  ExportDocSiteInput,
  SyncFromSourceInput,
  IngestTelemetryInput,
} from './types.js';
import {
  GenerateDocPageInputSchema,
  UpdateDocPageInputSchema,
  ExportDocSiteInputSchema,
  SyncFromSourceInputSchema,
  IngestTelemetryInputSchema,
  DOCS_AUDIT_EVENTS,
  DOCS_PERMISSIONS,
} from './types.js';
import type { AppError } from '../../../errors.js';

interface DocsServiceDeps {
  authz: { authorize(ctx: RequestContext, action: string, resource?: string): Promise<Result<void, AppError>> };
  audit: { write(event: string, ctx: RequestContext, metadata: Record<string, unknown>): Promise<void> };
  ai: { generate(promptId: string, inputs: unknown, ctx: RequestContext): Promise<Result<unknown, AppError>> };
  logger: { error(msg: string, meta?: unknown): void };
}

export class DocsService {
  constructor(private readonly deps: DocsServiceDeps) {}

  async generateDocPage(
    ctx: RequestContext,
    input: GenerateDocPageInput,
  ): Promise<Result<DocPage, AppError>> {
    const parsed = GenerateDocPageInputSchema.safeParse(input);
    if (!parsed.success) return err(new ValidationError('Invalid input', parsed.error.flatten()));

    const authzResult = await this.deps.authz.authorize(ctx, DOCS_PERMISSIONS.WRITE);
    if (authzResult.isErr()) return err(authzResult.error);

    const genResult = await this.deps.ai.generate('docs.schema-page-generation', {
      sourceType: parsed.data.sourceType,
      sourceContent: parsed.data.sourceContent,
    }, ctx);
    if (genResult.isErr()) return err(genResult.error);

    const generated = genResult.value as { title: string; description: string; sections: Array<{ heading: string; content: string }> };

    const page: DocPage = {
      id: `page-${Date.now()}`,
      workspaceId: ctx.workspaceId,
      appId: parsed.data.appId,
      slug: parsed.data.existingSlug ?? `/${parsed.data.sourceType}/${parsed.data.sourceId}`,
      title: generated.title,
      description: generated.description,
      sections: generated.sections.map((s, i) => ({
        id: `section-${i}`,
        heading: s.heading,
        content: s.content,
        sourceType: parsed.data.sourceType,
        autoGenerated: true,
        lastUpdatedAt: new Date().toISOString(),
      })),
      status: 'draft',
      autoGeneratedPercent: 100,
      linkedSurfaces: [],
      sourceType: parsed.data.sourceType,
      lastSyncedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    await this.deps.audit.write(DOCS_AUDIT_EVENTS.DOC_PAGE_CREATED, ctx, {
      pageId: page.id,
      sourceType: parsed.data.sourceType,
      sourceId: parsed.data.sourceId,
    });

    return ok(page);
  }

  async getDocPage(ctx: RequestContext, pageId: string): Promise<Result<DocPage, AppError>> {
    const authzResult = await this.deps.authz.authorize(ctx, DOCS_PERMISSIONS.READ);
    if (authzResult.isErr()) return err(authzResult.error);

    // Storage lookup would go here
    return err(new NotFoundError(`Doc page ${pageId} not found`));
  }

  async listDocPages(ctx: RequestContext, appId: string): Promise<Result<DocPage[], AppError>> {
    const authzResult = await this.deps.authz.authorize(ctx, DOCS_PERMISSIONS.READ);
    if (authzResult.isErr()) return err(authzResult.error);

    return ok([]);
  }

  async updateDocPage(
    ctx: RequestContext,
    input: UpdateDocPageInput,
  ): Promise<Result<DocPage, AppError>> {
    const parsed = UpdateDocPageInputSchema.safeParse(input);
    if (!parsed.success) return err(new ValidationError('Invalid input', parsed.error.flatten()));

    const authzResult = await this.deps.authz.authorize(ctx, DOCS_PERMISSIONS.WRITE);
    if (authzResult.isErr()) return err(authzResult.error);

    await this.deps.audit.write(DOCS_AUDIT_EVENTS.DOC_PAGE_UPDATED, ctx, {
      pageId: parsed.data.pageId,
      sectionId: parsed.data.sectionId,
    });

    return err(new NotFoundError(`Doc page ${parsed.data.pageId} not found`));
  }

  async syncFromSource(
    ctx: RequestContext,
    input: SyncFromSourceInput,
  ): Promise<Result<{ syncedPages: number }, AppError>> {
    const parsed = SyncFromSourceInputSchema.safeParse(input);
    if (!parsed.success) return err(new ValidationError('Invalid input', parsed.error.flatten()));

    const authzResult = await this.deps.authz.authorize(ctx, DOCS_PERMISSIONS.WRITE);
    if (authzResult.isErr()) return err(authzResult.error);

    // Async: find all pages with matching sourceType, regenerate each
    this._syncPagesAsync(ctx, parsed.data).catch((e: unknown) =>
      this.deps.logger.error('Async doc sync failed', e),
    );

    return ok({ syncedPages: 0 });
  }

  private async _syncPagesAsync(ctx: RequestContext, input: SyncFromSourceInput): Promise<void> {
    await this.deps.audit.write(DOCS_AUDIT_EVENTS.DOC_PAGE_SYNCED, ctx, {
      appId: input.appId,
      sourceType: input.trigger.sourceType,
      sourceId: input.trigger.sourceId,
    });
  }

  async exportDocSite(
    ctx: RequestContext,
    input: ExportDocSiteInput,
  ): Promise<Result<DocExport, AppError>> {
    const parsed = ExportDocSiteInputSchema.safeParse(input);
    if (!parsed.success) return err(new ValidationError('Invalid input', parsed.error.flatten()));

    const authzResult = await this.deps.authz.authorize(ctx, DOCS_PERMISSIONS.EXPORT);
    if (authzResult.isErr()) return err(authzResult.error);

    const docExport: DocExport = {
      id: `export-${Date.now()}`,
      workspaceId: ctx.workspaceId,
      appId: parsed.data.appId,
      version: parsed.data.version,
      status: 'generating',
      telemetryEnabled: parsed.data.telemetryEnabled,
      createdAt: new Date().toISOString(),
    };

    await this.deps.audit.write(DOCS_AUDIT_EVENTS.DOC_EXPORT_STARTED, ctx, {
      exportId: docExport.id,
      version: parsed.data.version,
      telemetryEnabled: parsed.data.telemetryEnabled,
    });

    // Async: build Next.js + fumadocs project, zip, upload
    this._buildExportAsync(ctx, docExport).catch((e: unknown) =>
      this.deps.logger.error('Async doc export failed', e),
    );

    return ok(docExport);
  }

  private async _buildExportAsync(ctx: RequestContext, docExport: DocExport): Promise<void> {
    await this.deps.audit.write(DOCS_AUDIT_EVENTS.DOC_EXPORT_COMPLETED, ctx, {
      exportId: docExport.id,
      version: docExport.version,
    });
  }

  async getDocExport(ctx: RequestContext, exportId: string): Promise<Result<DocExport, AppError>> {
    const authzResult = await this.deps.authz.authorize(ctx, DOCS_PERMISSIONS.READ);
    if (authzResult.isErr()) return err(authzResult.error);

    return err(new NotFoundError(`Doc export ${exportId} not found`));
  }

  async listDocExports(ctx: RequestContext, appId: string): Promise<Result<DocExport[], AppError>> {
    const authzResult = await this.deps.authz.authorize(ctx, DOCS_PERMISSIONS.READ);
    if (authzResult.isErr()) return err(authzResult.error);

    return ok([]);
  }

  async ingestTelemetry(
    ctx: RequestContext,
    input: IngestTelemetryInput,
  ): Promise<Result<DocTelemetryEvent, AppError>> {
    const parsed = IngestTelemetryInputSchema.safeParse(input);
    if (!parsed.success) return err(new ValidationError('Invalid input', parsed.error.flatten()));

    const authzResult = await this.deps.authz.authorize(ctx, DOCS_PERMISSIONS.TELEMETRY_RECEIVE);
    if (authzResult.isErr()) return err(authzResult.error);

    const event: DocTelemetryEvent = {
      id: `tel-${Date.now()}`,
      workspaceId: ctx.workspaceId,
      appId: parsed.data.appId,
      exportVersion: parsed.data.exportVersion,
      event: parsed.data.event,
      page: parsed.data.page,
      searchQuery: parsed.data.searchQuery,
      durationMs: parsed.data.durationMs,
      timestamp: parsed.data.timestamp,
      receivedAt: new Date().toISOString(),
    };

    await this.deps.audit.write(DOCS_AUDIT_EVENTS.DOC_TELEMETRY_RECEIVED, ctx, {
      exportVersion: event.exportVersion,
      event: event.event,
      page: event.page,
    });

    return ok(event);
  }

  async configureSite(ctx: RequestContext, appId: string, config: DocSite['config']): Promise<Result<DocSite, AppError>> {
    const authzResult = await this.deps.authz.authorize(ctx, DOCS_PERMISSIONS.CONFIGURE);
    if (authzResult.isErr()) return err(authzResult.error);

    const site: DocSite = {
      id: `site-${appId}`,
      workspaceId: ctx.workspaceId,
      appId,
      config,
      pageCount: 0,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    await this.deps.audit.write(DOCS_AUDIT_EVENTS.DOC_SITE_CONFIGURED, ctx, { appId });

    return ok(site);
  }
}
