import { z } from 'zod';

// ── Source types ─────────────────────────────────────────────────────────────

export type DocSourceType =
  | 'schema'
  | 'api_rest'
  | 'api_graphql'
  | 'ui_component'
  | 'webhook_config'
  | 'auth_config'
  | 'deployment_event'
  | 'prd'
  | 'human_maintained';

export type DocPageStatus = 'draft' | 'published' | 'stale';

export type DocExportStatus = 'pending' | 'generating' | 'ready' | 'failed';

// ── Core entities ─────────────────────────────────────────────────────────────

export interface DocSection {
  id: string;
  heading: string;
  content: string;
  sourceType: DocSourceType;
  autoGenerated: boolean;
  lastUpdatedAt: string;
}

export interface DocPage {
  id: string;
  workspaceId: string;
  appId: string;
  slug: string;
  title: string;
  description?: string;
  sections: DocSection[];
  status: DocPageStatus;
  autoGeneratedPercent: number;
  linkedSurfaces: string[];
  sourceType: DocSourceType;
  lastSyncedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface DocSiteConfig {
  siteName: string;
  logoUrl?: string;
  primaryColor?: string;
  telemetryEnabled: boolean;
  searchEnabled: boolean;
  sections: string[];
}

export interface DocSite {
  id: string;
  workspaceId: string;
  appId: string;
  config: DocSiteConfig;
  pageCount: number;
  lastPublishedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface DocExport {
  id: string;
  workspaceId: string;
  appId: string;
  version: string;
  status: DocExportStatus;
  telemetryEnabled: boolean;
  downloadUrl?: string;
  sizeBytes?: number;
  errorMessage?: string;
  createdAt: string;
  completedAt?: string;
}

export interface DocTelemetryEvent {
  id: string;
  workspaceId: string;
  appId: string;
  exportVersion: string;
  event: 'page_view' | 'search' | 'link_click';
  page: string;
  searchQuery?: string;
  durationMs?: number;
  timestamp: string;
  receivedAt: string;
}

export interface DocSyncTrigger {
  sourceType: DocSourceType;
  sourceId: string;
  changeDescription?: string;
}

export type DocsAuditEventType =
  | 'DOC_PAGE_CREATED'
  | 'DOC_PAGE_UPDATED'
  | 'DOC_PAGE_PUBLISHED'
  | 'DOC_PAGE_SYNCED'
  | 'DOC_SITE_CONFIGURED'
  | 'DOC_EXPORT_STARTED'
  | 'DOC_EXPORT_COMPLETED'
  | 'DOC_EXPORT_FAILED'
  | 'DOC_TELEMETRY_RECEIVED';

export const DOCS_AUDIT_EVENTS: Record<DocsAuditEventType, DocsAuditEventType> = {
  DOC_PAGE_CREATED: 'DOC_PAGE_CREATED',
  DOC_PAGE_UPDATED: 'DOC_PAGE_UPDATED',
  DOC_PAGE_PUBLISHED: 'DOC_PAGE_PUBLISHED',
  DOC_PAGE_SYNCED: 'DOC_PAGE_SYNCED',
  DOC_SITE_CONFIGURED: 'DOC_SITE_CONFIGURED',
  DOC_EXPORT_STARTED: 'DOC_EXPORT_STARTED',
  DOC_EXPORT_COMPLETED: 'DOC_EXPORT_COMPLETED',
  DOC_EXPORT_FAILED: 'DOC_EXPORT_FAILED',
  DOC_TELEMETRY_RECEIVED: 'DOC_TELEMETRY_RECEIVED',
};

export const DOCS_PERMISSIONS = {
  READ: 'docs.read',
  WRITE: 'docs.write',
  EXPORT: 'docs.export',
  CONFIGURE: 'docs.configure',
  TELEMETRY_RECEIVE: 'docs.telemetry.receive',
} as const;

export const DOCS_DEFAULT_GRANTS = {
  admin: ['docs.read', 'docs.write', 'docs.export', 'docs.configure', 'docs.telemetry.receive'],
  developer: ['docs.read', 'docs.write', 'docs.export'],
  viewer: ['docs.read'],
};

// ── Input schemas ─────────────────────────────────────────────────────────────

export const GenerateDocPageInputSchema = z.object({
  appId: z.string().min(1),
  sourceType: z.enum([
    'schema', 'api_rest', 'api_graphql', 'ui_component',
    'webhook_config', 'auth_config', 'deployment_event', 'prd',
  ]),
  sourceId: z.string().min(1),
  sourceContent: z.string().min(1),
  existingSlug: z.string().optional(),
});

export const UpdateDocPageInputSchema = z.object({
  pageId: z.string().min(1),
  sectionId: z.string().min(1),
  content: z.string().min(1),
});

export const ExportDocSiteInputSchema = z.object({
  appId: z.string().min(1),
  version: z.string().min(1),
  telemetryEnabled: z.boolean().default(true),
});

export const SyncFromSourceInputSchema = z.object({
  appId: z.string().min(1),
  trigger: z.object({
    sourceType: z.enum([
      'schema', 'api_rest', 'api_graphql', 'ui_component',
      'webhook_config', 'auth_config', 'deployment_event', 'prd',
    ]),
    sourceId: z.string().min(1),
    changeDescription: z.string().optional(),
  }),
});

export const IngestTelemetryInputSchema = z.object({
  exportVersion: z.string().min(1),
  appId: z.string().min(1),
  event: z.enum(['page_view', 'search', 'link_click']),
  page: z.string().min(1),
  searchQuery: z.string().optional(),
  durationMs: z.number().optional(),
  timestamp: z.string().datetime(),
});

export type GenerateDocPageInput = z.infer<typeof GenerateDocPageInputSchema>;
export type UpdateDocPageInput = z.infer<typeof UpdateDocPageInputSchema>;
export type ExportDocSiteInput = z.infer<typeof ExportDocSiteInputSchema>;
export type SyncFromSourceInput = z.infer<typeof SyncFromSourceInputSchema>;
export type IngestTelemetryInput = z.infer<typeof IngestTelemetryInputSchema>;
