'use client';

import { Zap, Pencil } from 'lucide-react';

import type { DocNavItem } from '../page';

const DEMO_CONTENT: Record<
  string,
  {
    autoPercent: number;
    sections: Array<{ heading: string; content: string; autoGenerated: boolean }>;
  }
> = {
  quickstart: {
    autoPercent: 30,
    sections: [
      {
        heading: "What you'll build",
        content:
          "In this guide you'll authenticate with the API and create your first Contact record.",
        autoGenerated: false,
      },
      {
        heading: 'Authentication',
        content:
          'All API requests require an `Authorization: Bearer <token>` header. Generate a token in **Settings → API Keys**.',
        autoGenerated: false,
      },
      {
        heading: 'Create your first contact',
        content:
          '```bash\ncurl -X POST https://api.example.com/v1/contacts \\\n  -H "Authorization: Bearer $TOKEN" \\\n  -d \'{"email":"alice@example.com","name":"Alice"}\'\n```',
        autoGenerated: true,
      },
    ],
  },
  contact: {
    autoPercent: 100,
    sections: [
      {
        heading: 'Overview',
        content:
          'A Contact represents an individual person in the system. Contacts are the primary entity in the CRM.',
        autoGenerated: true,
      },
      {
        heading: 'Fields',
        content:
          '| Field | Type | Required | Description |\n|---|---|---|---|\n| `id` | `uuid` | ✓ | Unique identifier |\n| `email` | `string` | ✓ | Contact email |\n| `name` | `string` | ✓ | Full name |\n| `ownerId` | `uuid` | — | Assigned owner |',
        autoGenerated: true,
      },
    ],
  },
};

function renderMarkdown(content: string) {
  return content
    .split('\n')
    .map((line, i) => {
      if (line.startsWith('```')) return null;
      if (line.startsWith('| ') || line.startsWith('|---')) {
        return (
          <span key={i} className="pg-mono" style={{ fontSize: 12, display: 'block' }}>
            {line}
          </span>
        );
      }
      if (line.startsWith('#')) {
        return (
          <p key={i} style={{ fontWeight: 500, marginTop: 8 }}>
            {line.replace(/^#+\s/, '')}
          </p>
        );
      }
      return (
        <span key={i} style={{ display: 'block' }}>
          {line}
        </span>
      );
    })
    .filter(Boolean);
}

export function DocContent({ page }: { page: DocNavItem }) {
  const content = DEMO_CONTENT[page.id] ?? {
    autoPercent: page.autoGenerated ? 95 : 10,
    sections: [
      {
        heading: 'Overview',
        content: `This page documents the **${page.title}** surface. Content is ${page.autoGenerated ? 'auto-generated from the ' + page.sourceType + ' artifact.' : 'human-maintained.'}`,
        autoGenerated: page.autoGenerated,
      },
    ],
  };

  return (
    <div style={{ maxWidth: 720, margin: '0 auto', padding: 32 }}>
      <div style={{ marginBottom: 24 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 8 }}>
          <h1 style={{ fontSize: 22, fontWeight: 700, color: 'var(--fg-primary)', margin: 0 }}>
            {page.title}
          </h1>
          {page.autoGenerated && (
            <span
              className="pg-badge pg-badge-warning"
              style={{ display: 'flex', alignItems: 'center', gap: 4 }}
            >
              <Zap style={{ width: 11, height: 11 }} />
              Auto-generated
            </span>
          )}
        </div>

        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: 8,
            fontSize: 13,
            color: 'var(--fg-tertiary)',
          }}
        >
          <span>{content.autoPercent}% auto-generated</span>
          <span>·</span>
          <span>Source: {page.sourceType.replace('_', ' ')}</span>
        </div>

        <div
          style={{
            marginTop: 8,
            height: 6,
            borderRadius: 3,
            background: 'var(--border-default)',
            overflow: 'hidden',
          }}
        >
          <div
            style={{
              height: '100%',
              background: 'var(--fg-warning)',
              borderRadius: 3,
              transition: 'width 0.3s',
              width: `${String(content.autoPercent)}%`,
            }}
          />
        </div>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 32 }}>
        {content.sections.map((section, i) => (
          <div key={i} className="group">
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 12 }}>
              <h2 style={{ fontSize: 16, fontWeight: 600, color: 'var(--fg-primary)', margin: 0 }}>
                {section.heading}
              </h2>
              {section.autoGenerated && (
                <Zap style={{ width: 13, height: 13, color: 'var(--fg-warning)', opacity: 0.6 }} />
              )}
              {!section.autoGenerated && (
                <button className="pg-btn pg-btn-ghost pg-btn-xs" style={{ opacity: 0 }}>
                  <Pencil style={{ width: 11, height: 11, marginRight: 4 }} />
                  Edit
                </button>
              )}
            </div>
            <div style={{ fontSize: 13, lineHeight: 1.6, color: 'var(--fg-secondary)' }}>
              {renderMarkdown(section.content)}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
