'use client';

import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Zap, Pencil } from 'lucide-react';
import type { DocNavItem } from '../page';

const DEMO_CONTENT: Record<string, { autoPercent: number; sections: Array<{ heading: string; content: string; autoGenerated: boolean }> }> = {
  quickstart: {
    autoPercent: 30,
    sections: [
      {
        heading: 'What you\'ll build',
        content: 'In this guide you\'ll authenticate with the API and create your first Contact record.',
        autoGenerated: false,
      },
      {
        heading: 'Authentication',
        content: 'All API requests require an `Authorization: Bearer <token>` header. Generate a token in **Settings → API Keys**.',
        autoGenerated: false,
      },
      {
        heading: 'Create your first contact',
        content: '```bash\ncurl -X POST https://api.example.com/v1/contacts \\\n  -H "Authorization: Bearer $TOKEN" \\\n  -d \'{"email":"alice@example.com","name":"Alice"}\'\n```',
        autoGenerated: true,
      },
    ],
  },
  contact: {
    autoPercent: 100,
    sections: [
      {
        heading: 'Overview',
        content: 'A Contact represents an individual person in the system. Contacts are the primary entity in the CRM.',
        autoGenerated: true,
      },
      {
        heading: 'Fields',
        content: '| Field | Type | Required | Description |\n|---|---|---|---|\n| `id` | `uuid` | ✓ | Unique identifier |\n| `email` | `string` | ✓ | Contact email |\n| `name` | `string` | ✓ | Full name |\n| `ownerId` | `uuid` | — | Assigned owner |',
        autoGenerated: true,
      },
    ],
  },
};

function renderMarkdown(content: string) {
  // Simple inline renderer — in production this would use a proper MDX renderer
  return content
    .split('\n')
    .map((line, i) => {
      if (line.startsWith('```')) return null;
      if (line.startsWith('| ') || line.startsWith('|---')) {
        return <span key={i} className="font-mono text-xs block">{line}</span>;
      }
      if (line.startsWith('#')) {
        return <p key={i} className="font-medium mt-2">{line.replace(/^#+\s/, '')}</p>;
      }
      return <span key={i} className="block">{line}</span>;
    })
    .filter(Boolean);
}

export function DocContent({ page }: { page: DocNavItem }) {
  const content = DEMO_CONTENT[page.id] ?? {
    autoPercent: page.autoGenerated ? 95 : 10,
    sections: [
      {
        heading: 'Overview',
        content: `This page documents the **${page.title}** surface. Content is ${page.autoGenerated ? 'auto-generated from the ' + page.sourceType + ' artifact.' : 'human-maintained.'}`,
        autoGenerated: page.autoGenerated,
      },
    ],
  };

  return (
    <div className="max-w-3xl mx-auto px-8 py-8">
      <div className="mb-6">
        <div className="flex items-center gap-3 mb-2">
          <h1 className="text-2xl font-bold">{page.title}</h1>
          {page.autoGenerated && (
            <Badge variant="secondary" className="gap-1 text-xs">
              <Zap className="h-3 w-3 text-amber-500" />
              Auto-generated
            </Badge>
          )}
        </div>

        <div className="flex items-center gap-2 text-sm text-muted-foreground">
          <span>{content.autoPercent}% auto-generated</span>
          <span>·</span>
          <span>Source: {page.sourceType.replace('_', ' ')}</span>
        </div>

        <div className="mt-2 h-1.5 rounded-full bg-muted overflow-hidden">
          <div
            className="h-full bg-amber-400 rounded-full transition-all"
            style={{ width: `${content.autoPercent}%` }}
          />
        </div>
      </div>

      <div className="space-y-8">
        {content.sections.map((section, i) => (
          <div key={i} className="group">
            <div className="flex items-center gap-2 mb-3">
              <h2 className="text-lg font-semibold">{section.heading}</h2>
              {section.autoGenerated && <Zap className="h-3.5 w-3.5 text-amber-400 opacity-60" />}
              {!section.autoGenerated && (
                <Button size="sm" variant="ghost" className="h-6 px-2 opacity-0 group-hover:opacity-100 transition-opacity">
                  <Pencil className="h-3 w-3 mr-1" />
                  Edit
                </Button>
              )}
            </div>
            <div className="text-sm leading-relaxed text-foreground/90 prose prose-sm max-w-none">
              {renderMarkdown(section.content)}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
