'use client';

import { ExternalLink, Zap, Clock, Link2 } from 'lucide-react';

import type { DocNavItem } from '../page';

const LINKED_SURFACES: Record<string, string[]> = {
  contact: [
    'Schema Designer â†’ Contact entity',
    'API Reference â†’ GET /contacts',
    'ContactsTable component',
  ],
  'api-rest': ['Stage 7: API Generation', 'Deployment: REST endpoints'],
  'contacts-table': ['Stage 6: UI Generation', 'Schema: Contact entity'],
};

export function DocMetaPanel({ page }: { page: DocNavItem }) {
  const linkedSurfaces = LINKED_SURFACES[page.id] ?? [];

  return (
    <div
      style={{
        width: 224,
        flexShrink: 0,
        borderLeft: '1px solid var(--border)',
        overflowY: 'auto',
        padding: '16px 16px',
        display: 'flex',
        flexDirection: 'column',
        gap: 20,
      }}
    >
      <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
        <p
          style={{
            fontSize: 11,
            fontWeight: 600,
            textTransform: 'uppercase',
            letterSpacing: '0.06em',
            margin: 0,
          }}
        >
          Page info
        </p>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 12 }}>
            <Clock style={{ width: 13, height: 13 }} />
            <span>Updated 2h ago</span>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 12 }}>
            <Zap style={{ width: 13, height: 13 }} />
            <span>
              Source: <span>{page.sourceType.replace('_', ' ')}</span>
            </span>
          </div>
        </div>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
        <p
          style={{
            fontSize: 11,
            fontWeight: 600,
            textTransform: 'uppercase',
            letterSpacing: '0.06em',
            margin: 0,
          }}
        >
          Status
        </p>
        <span
          className={
            page.autoGenerated
              ? 'inline-flex items-center rounded-full bg-amber-100 px-2 py-0.5 text-[11px] font-medium text-amber-700 dark:bg-amber-900/30 dark:text-amber-400'
              : 'inline-flex items-center rounded-full bg-muted px-2 py-0.5 text-[11px] font-medium text-muted-foreground'
          }
          style={{ display: 'inline-flex', alignItems: 'center', gap: 4, width: 'fit-content' }}
        >
          {page.autoGenerated ? (
            <>
              <Zap style={{ width: 11, height: 11 }} />
              Auto-generated
            </>
          ) : (
            'Human-maintained'
          )}
        </span>
      </div>

      {linkedSurfaces.length > 0 && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          <p
            style={{
              fontSize: 11,
              fontWeight: 600,
              textTransform: 'uppercase',
              letterSpacing: '0.06em',
              margin: 0,
              display: 'flex',
              alignItems: 'center',
              gap: 4,
            }}
          >
            <Link2 style={{ width: 11, height: 11 }} />
            Linked surfaces
          </p>
          <ul
            style={{
              listStyle: 'none',
              padding: 0,
              margin: 0,
              display: 'flex',
              flexDirection: 'column',
              gap: 6,
            }}
          >
            {linkedSurfaces.map((s, i) => (
              <li key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: 6 }}>
                <ExternalLink
                  style={{
                    width: 11,
                    height: 11,
                    marginTop: 2,
                    flexShrink: 0,
                  }}
                />
                <span style={{ fontSize: 12, lineHeight: 1.4 }}>{s}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
        <p
          style={{
            fontSize: 11,
            fontWeight: 600,
            textTransform: 'uppercase',
            letterSpacing: '0.06em',
            margin: 0,
          }}
        >
          Auto-gen bar
        </p>
        <p style={{ fontSize: 12, margin: 0 }}>
          {page.autoGenerated
            ? 'This page updates automatically when its source artifact changes.'
            : 'This page is manually maintained and will not auto-update.'}
        </p>
      </div>
    </div>
  );
}
