'use client';

import { Badge } from '@/components/ui/badge';
import { ExternalLink, Zap, Clock, Link2 } from 'lucide-react';
import type { DocNavItem } from '../page';

const LINKED_SURFACES: Record<string, string[]> = {
  contact: ['Schema Designer → Contact entity', 'API Reference → GET /contacts', 'ContactsTable component'],
  'api-rest': ['Stage 7: API Generation', 'Deployment: REST endpoints'],
  'contacts-table': ['Stage 6: UI Generation', 'Schema: Contact entity'],
};

export function DocMetaPanel({ page }: { page: DocNavItem }) {
  const linkedSurfaces = LINKED_SURFACES[page.id] ?? [];

  return (
    <div className="w-56 shrink-0 border-l overflow-y-auto py-4 px-4 space-y-5">
      <div className="space-y-2">
        <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Page info</p>

        <div className="space-y-1.5">
          <div className="flex items-center gap-2 text-xs">
            <Clock className="h-3.5 w-3.5 text-muted-foreground" />
            <span className="text-muted-foreground">Updated 2h ago</span>
          </div>

          <div className="flex items-center gap-2 text-xs">
            <Zap className="h-3.5 w-3.5 text-amber-500" />
            <span className="text-muted-foreground">
              Source: <span className="text-foreground">{page.sourceType.replace('_', ' ')}</span>
            </span>
          </div>
        </div>
      </div>

      <div className="space-y-2">
        <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Status</p>
        <Badge variant={page.autoGenerated ? 'secondary' : 'outline'} className="text-xs gap-1">
          {page.autoGenerated ? <><Zap className="h-3 w-3 text-amber-500" />Auto-generated</> : 'Human-maintained'}
        </Badge>
      </div>

      {linkedSurfaces.length > 0 && (
        <div className="space-y-2">
          <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide flex items-center gap-1">
            <Link2 className="h-3 w-3" />
            Linked surfaces
          </p>
          <ul className="space-y-1.5">
            {linkedSurfaces.map((s, i) => (
              <li key={i} className="flex items-start gap-1.5">
                <ExternalLink className="h-3 w-3 mt-0.5 shrink-0 text-muted-foreground" />
                <span className="text-xs text-muted-foreground leading-snug">{s}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      <div className="space-y-2">
        <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Auto-gen bar</p>
        <p className="text-xs text-muted-foreground">
          {page.autoGenerated
            ? 'This page updates automatically when its source artifact changes.'
            : 'This page is manually maintained and will not auto-update.'}
        </p>
      </div>
    </div>
  );
}
