'use client';

import { useState } from 'react';
import { ChevronRight, ChevronDown, Zap } from 'lucide-react';
import type { DocNavItem } from '../page';

interface Props {
  items: DocNavItem[];
  activePage: DocNavItem;
  onNavigate: (item: DocNavItem) => void;
}

function NavItem({ item, activePage, onNavigate, depth = 0 }: {
  item: DocNavItem;
  activePage: DocNavItem;
  onNavigate: (item: DocNavItem) => void;
  depth?: number;
}) {
  const [expanded, setExpanded] = useState(true);
  const hasChildren = item.children && item.children.length > 0;
  const isActive = item.id === activePage.id;

  return (
    <div>
      <div
        className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md cursor-pointer transition-colors text-sm
          ${isActive ? 'bg-primary/10 text-primary font-medium' : 'hover:bg-muted/50 text-foreground/80'}
        `}
        style={{ paddingLeft: `${12 + depth * 16}px` }}
        onClick={() => {
          if (hasChildren) setExpanded(e => !e);
          onNavigate(item);
        }}
      >
        {hasChildren ? (
          expanded
            ? <ChevronDown className="h-3.5 w-3.5 shrink-0 text-muted-foreground" />
            : <ChevronRight className="h-3.5 w-3.5 shrink-0 text-muted-foreground" />
        ) : (
          <span className="w-3.5 shrink-0" />
        )}

        <span className="truncate flex-1">{item.title}</span>

        {item.autoGenerated && (
          <Zap className="h-3 w-3 shrink-0 text-amber-500" title="Auto-generated" />
        )}
      </div>

      {hasChildren && expanded && (
        <div>
          {item.children!.map(child => (
            <NavItem
              key={child.id}
              item={child}
              activePage={activePage}
              onNavigate={onNavigate}
              depth={depth + 1}
            />
          ))}
        </div>
      )}
    </div>
  );
}

export function DocSidebar({ items, activePage, onNavigate }: Props) {
  return (
    <div className="w-56 shrink-0 border-r overflow-y-auto py-3">
      <div className="px-3 mb-2">
        <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Contents</p>
      </div>
      <div className="space-y-0.5">
        {items.map(item => (
          <NavItem key={item.id} item={item} activePage={activePage} onNavigate={onNavigate} />
        ))}
      </div>

      <div className="px-3 mt-4 pt-3 border-t">
        <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
          <Zap className="h-3 w-3 text-amber-500" />
          <span>Auto-generated</span>
        </div>
      </div>
    </div>
  );
}
