export { MaintenanceService } from './maintenance.service.js';
export type {
  SignalSource,
  SignalSeverity,
  SignalStatus,
  ErrorSignalDetails,
  PerfSignalDetails,
  UserReportDetails,
  DependencyAdvisoryDetails,
  StageClassificationEntry,
  SignalClassification,
  Signal,
  ChangeRequestStatus,
  ChangeRequestPriority,
  OutcomeMetrics,
  ChangeRequest,
  DependencyAdvisory,
  CascadeStatus,
  AffectedArtifact,
  AffectedDownstreamReport,
  OutcomeReport,
  MaintenanceQualitySignals,
  IngestSignalInput,
  CreateChangeRequestInput,
  ResolveChangeRequestInput,
  MaintenanceAuditEventType,
} from './types.js';
export {
  IngestSignalInputSchema,
  CreateChangeRequestInputSchema,
  ResolveChangeRequestInputSchema,
  MAINTENANCE_AUDIT_EVENTS,
  MAINTENANCE_PERMISSIONS,
  MAINTENANCE_DEFAULT_GRANTS,
} from './types.js';
